import React from 'react'
import styled, {createGlobalStyle} from "styled-components"
import circle from "../svg/circle.svg"



const StyledSquare = styled.div`
margin: ${props => props.margin || "48% 0 0 9px"};
position: absolute;
height: 201px;
width: 13.95%;
z-index: 3;
display: grid;
column-gap: 4.477%;
row-gap: 4.477%;
grid-template-columns: repeat(16, 1fr)
`
function Square({ ...props}) {
    return (
        <StyledSquare {...props}>
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />
            <img width = {"4px"} height={"4px"} src={circle} alt="circle" />

        </StyledSquare>
    )
}

export default Square